### ISSUE TITLE
Bug encountered when I run PEMS_BAY

### ISSUE THREAD

**Issue by KL4805** [HKUDS/OpenCity#6]
Dear authors, 

Thanks for your great work! 

I was trying to run your model on the dataset 'PEMS_BAY'. I downloaded OpenCity-Plus from Huggingface, downloaded PEMS_BAY from your dataset, and run 

```
python Run.py -mode test -model OpenCity -load_pretrain_path OpenCity-plus.pth -batch_size 2 --embed_dim 512 --skip_dim 512 --enc_depth 6
```

It ran very well for the first steps, until the following error popped out. 

```
13056 tensor(1.7145, device='cuda:0') tensor(3.6624, device='cuda:0') tensor(0.0331, device='cuda:0') 1222015392 1222015392
13120 tensor(1.5592, device='cuda:0') tensor(3.1834, device='cuda:0') tensor(0.0285, device='cuda:0') 1228005792 1228005792
13184 tensor(1.4364, device='cuda:0') tensor(2.8701, device='cuda:0') tensor(0.0249, device='cuda:0') 1233996192 1233996192
13248 tensor(1.4072, device='cuda:0') tensor(3.0303, device='cuda:0') tensor(0.0252, device='cuda:0') 1239986592 1239986592
Traceback (most recent call last):
  File "Run.py", line 152, in <module>
    trainer.test(model, trainer.args, scaler_dict, test_dataloader, trainer.logger, path=log_dir + '/' + args.load_pretrain_path)
  File "/data/glusterfs/home/yilun/OpenCity-main/model/BasicTrainer.py", line 155, in test
    output = model(inputs, targets, select_dataset, batch_seen=None)
  File "/data/glusterfs/home/yilun/miniconda3/envs/huggingface/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/glusterfs/home/yilun/miniconda3/envs/huggingface/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/glusterfs/home/yilun/miniconda3/envs/huggingface/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/data/glusterfs/home/yilun/miniconda3/envs/huggingface/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data/glusterfs/home/yilun/miniconda3/envs/huggingface/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/data/glusterfs/home/yilun/miniconda3/envs/huggingface/lib/python3.8/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/data/glusterfs/home/yilun/miniconda3/envs/huggingface/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
  File "/data/glusterfs/home/yilun/miniconda3/envs/huggingface/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/glusterfs/home/yilun/miniconda3/envs/huggingface/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() missing 3 required positional arguments: 'source', 'label', and 'select_dataset'
```

Could you please check what may be the cause of the problem? 

For your information, the error did not pop out when I evaluate on METR-LA.

**Comment by LZH-YS1998** [comment]
Thank you for your attention! I think the issue might be caused by using 2 GPUs, which results in the last batch size being 1. If you evaluate using only 1 GPU, the problem should be resolved.

"last batch torch.Size([1, 288, 325, 1]) torch.Size([1, 288, 325, 1])"

**Comment by KL4805** [comment]
Thank you. The problem seems to be resolved.
